name: Deploiement d'Apache sur LXC

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Déployer avec Ansible
      run: |
        cd ansible
        ansible-playbook -i etc/hosts -u root playbooks/recette.yml -v
